theme: jekyll-theme-minimal

title: Repository of public projects
description: Various project by Carlos Neves, Bioinformatician at [Fios Genomics](https://www.fiosgenomics.com/) and 
Data Science Mentor at [Thinkful](https://www.thinkful.com/)

logo: https://www.kaggle.com/static/images/host-home/host-home-research.png
show_downloads: "false"
