title: Data Science Portfolio
description: (Please note that the project list is currently being updated: last update 26/11/2018)
logo: https://www.kaggle.com/static/images/host-home/host-home-research.png
theme: jekyll-theme-minimal
