title: Repository of public projects
description: Various projects by Carlos Neves, Bioinformatician at [Fios Genomics](https://www.fiosgenomics.com/) and 
Data Science Mentor at [Thinkful](https://www.thinkful.com/)
show_downloads: false
future: true
theme: jekyll-theme-minimal
