title: Data Science Portfolio
description: &%28Please note that the project list is currently being updated&%3A last update 26/11/2018&%29
logo: https://www.kaggle.com/static/images/host-home/host-home-research.png
theme: jekyll-theme-minimal
