title: Repository of public projects
description: by [Carlos Neves](https://www.linkedin.com/in/carlos-neves-7b6a11b5/), Bioinformatician at [FiosGenomics](https://www.fiosgenomics.com/) and Data Science mentor at [Thinkful](https://www.thinkful.com/).
theme: jekyll-theme-minimal
