title: Data Science Portfolio
description: "(Please note that the project list is currently being updated: last update 31/01/2019)"
logo: https://www.kaggle.com/static/images/host-home/host-home-research.png
theme: jekyll-theme-minimal
